### ISSUE TITLE
Repository Not Code » NPM Start Fails`

### ISSUE THREAD

**Issue by rjksn** [Felistas/NodeJs-Passport-Authentication#9]
The website instructions as well as the readme both refer to this as a repository of code. Its master branch is instead a repository of images and a readme file.

Critical error in the instruction set since package.json does not exist in this repo.

```bash
$ mkdir demo
$ cd demo
$ git clone https://github.com/Felistas/NodeJs-Passport-Authentication.git
$ cd NodeJs-Passport-Authentication
```

Next run:
```
$ npm install
$ npm start
```

Maybe specifying a version/branch to use might work since there appears to be code in `complete-social-authentication`?

Thanks for the write up.

**Comment by Felistas** [comment]
Thanks for pointing this out. I will make the necessary adjustments.

**Comment by rjksn** [comment]
Thanks! Future googler's will be over joyed. :)
